= Contributing to the Embedded Linux Development with Yocto Project Bible book

== Licensing

By opening a pull request to this repository, you agree to provide your work under the [project license](LICENSE.adoc).

Also, you agree to grant such license of your work as is required for the purposes of future print editions to @otavio and @angolini.

Should your changes appear in a printed edition, you'll be included in the  link:book/contributors.adoc[contributors list].

== Small Corrections

Errata and basic clarifications will be accepted if we agree that they improve the content. You can also open an issue so we can figure out how or if it needs to be addressed.

If you've never done this before, the link:https://guides.github.com/introduction/flow/[flow guide] might be useful.

== Large Rewrites

Open an issue for discussion before you start. These changes tend to be very subjective, often only clarifying things for some small percentage of people and it's rarely worth the time to accept them.
