// SPDX-License-Identifier: CC-BY-SA-4.0
= Heading for the Yocto Project

Welcome to the first edition of the Heading for the Yocto Project book.

This book is free content. It is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License (`CC-BY-SA-4.0`). See the link:LICENSE[LICENSE] file for the full terms, and the link:NOTICE[NOTICE] file for the copyright holders.

== How To Generate the Book

To generate e-book files is to do so manually with Asciidoctor. If you run the following you _may_ actually get HTML, Epub, Mobi and PDF output files:

----
$ bundle exec rake build
(in /repo/ypbook)
Converting to HTML...
 -- HTML output at book/Heading-for-the-Yocto-Project.html
Converting to EPub...
 -- Epub output at book/Heading-for-the-Yocto-Project.epub
Converting to Mobi (kf8)...
 -- Mobi output at book/Heading-for-the-Yocto-Project.mobi
Converting to PDF... (this one takes a while)
asciidoctor: WARNING: conversion missing in backend pdf for pass
 -- PDF  output at book/Heading-for-the-Yocto-Project.pdf
----

This uses the `asciidoctor`, `asciidoctor-pdf` and `asciidoctor-epub` projects.

== Contributing

If you'd like to help out by making a change or contributing a translation, take a look at the link:CONTRIBUTING.adoc[contributor's guide].
