[[yp]]
== The Yocto Project

More and more software vendors and silicon manufactures are using the Yocto Project, bringing more users to the project, with varying backgrounds. This book aims to help everyone interested in understanding the reasons which has been driving the Yocto Project adoption without getting deeper in the technical details. The topics covered here assist in:

* Spotting possible benefits that the Yocto Project adoption can bring for your products;
* Choosing the best team organization and workflow for development with the Yocto Project;
* Improving the communication within the Yocto Project's community.

Ultimately, this book intends to ease the identification of projects and companies where the Yocto Project is the ideal framework to be used.

This first chapter focus in describing what the Yocto Project is, its core components and present the relationship between the Yocto Project with other projects and companies. It covers the following topics:

* What the Yocto Project is;
* What the main components of the Yocto Project are;
* The Poky build system and its components;
* A fraction of the history of the OpenEmbedded Project and how it ultimately got involved with the Yocto Project.

include::sections/What-the-Yocto-Project-is.adoc[]

include::sections/The-Yocto-Project-seen-as-a-Computing-Machine.adoc[]

include::sections/The-Poky-build-system.adoc[]

include::sections/The-alliance-of-OpenEmbedded-Project-and-Yocto-Project.adoc[]

:numbered!:
=== Summary
:numbered:

This first chapter, elucidates what the Yocto Project is, what the difference between the Poky and OpenEmbedded-Core build systems is and how all these projects relate to each other.

In the chapter <<Benefits for your products>>, we discuss the motivations that can lead you towards the Yocto Project, independently if you are an user, a developer or a company entrepreneur covering topics such as its advantages, risk reduction and platform reuse.
