[[yp]]
== The Yocto Project

More and more software vendors and silicon manufactures are using the Yocto Project bringing more users to the project, with varying backgrounds. This chapter has been crafted to be interesting for both beginners and experienced Yocto Project users, Linux enthusiasts and embedded systems lovers, as consequence.

This is our first dive in the Yocto Project ocean. We still remain close to the surface staring the project ecosystem from a safe distance until we get enough practice using our equipment. In following chapters, we go deeper in our dives finding extraordinary creatures, and outstanding surprises along the way.

This chapters focus in describing what the Yocto Project is, its core components and present the relationship between the Yocto Project with other projects and companies.

The chapter covers the following topics:

* What the Yocto Project is;
* What are the main components of the Yocto Project;
* The Poky build system and its components;
* A fraction of the history of the OpenEmbedded Project and how it ultimately  got involved with the Yocto Project.

So do the check of your equipment and dive with us!

include::sections/What-the-Yocto-Project-is.adoc[]

include::sections/The-Yocto-Project-seen-as-a-Computing-Machine.adoc[]

include::sections/The-Poky-build-system.adoc[]

include::sections/The-alliance-of-OpenEmbedded-Project-and-Yocto-Project.adoc[]

:numbered!:
=== Summary
:numbered:

This first dive, oops, chapter elucidates what is the Yocto Project, what is the difference between the Poky and OpenEmbedded-Core build systems and how all these projects relates to each other.

The choice for a very high abstraction level description is because this may be your very first contact with Yocto Project and the relationship between all project's components is hard to grasp when we look at the Yocto Project from a more inner technical perspective.

In the chapter <<Benefits for your products>>, we discuss the motivations that can lead you towards the Yocto Project, independently if you are an user, a developer or a company entrepreneur covering topics such as its advantages, risk reduction and platform reuse.
