== The Yocto Project community ecosystem

One of the biggest benefits of the Yocto Project is its community ecosystem.  In order to participate of this community it is important to develop the ability to properly communicate and contribute in a synergistic way.

This chapter gathers:

* The main communication channels used across the community
* Where to report or find information about known issues
* The expected behavior etiquette

include::sections/What-is-a-community.adoc[]

include::sections/The-Yocto-Projects-communication-channels.adoc[]

include::sections/Documentation.adoc[]

:numbered!:
=== Summary
:numbered:

This chapter may seem as taking sand to the beach for more experienced Free Software developers or long standing professional which are used to participate to communities however it is a general material for newcomers as the community ecosystem which surrounds the Yocto Project is one of the project’s biggest benefits. It consolidates the initial steps needed to start participating the Yocto Project community, which communication channels are commonly used by the Yocto Project community and general guidelines about good-practices while communicating across these channels.

We see the Yocto Project as a very exciting project and powerful framework which can be used in a number of companies and projects. Even though the deeper technical aspects related to the Yocto Project have not been covered in this book, it helps in understanding the reasons driving its adoption and providing enough background so it does not seem to be a black box anymore.
